### ISSUE TITLE
RSA Decryption of Data using YubiHSM2: Failed to decrypt data: Malformed command / invalid data

### ISSUE THREAD

**Issue by YoussKam** [Yubico/yubihsm-shell#260] opened 2022-05-11 07:09 UTC
We have an urgent issue to solve with the YubiHSM2 as we need to deliver our software end of this week.
In fact we are trying to decrypt an RSA encrypted data using the HSM but it is dont working.

We don't know what is missing in the process, should be
    * Key format excepted: DER,PEM
    * Key length
    * Data format excepted: DER, PEM
    * Data encryption algorithm: PKCS1 or other
Can you please help us?
Can you please use the following key to load a YubiHSM key and decrypt the data them inform us about the correct procedure?

Data are the following:
PublicKey: 30820120300D06092A864886F70D01010105000382010D00308201080282010100CEFE8906DA03CC8324F46D15EFC3332A1C385B239675CD0327E84DAFE1D51FF5692475487EA02EB72991A455965A4B9DF156D1996C30B1B3D4F2106B3EE9656E2C808D45DD8262B75C76E87D30B340A55D4081896EA15756E05A9E4B71F9E5CD6BB8C5DA2F6BD5240274777FBB5FD1C65C351DB1260DB9D12EA41F8F59F3EE2D643B6AE37350E5E8B1558FBF655D6309EB809599138D7746B14B8A60A07E5ED67F95A5660C72348F266642B6AE858D22558FB8B8024AE5B2749C0D5E32EBCF0E68422418D3A9214534BD45E526A868A39CC15A1572841A9ECD03D352EABA967EF62317307328138D953A85E11405F60A1CF812A84944D89DE1C34708AD38C1D9020103

PrivateKey: 308204C2020100300D06092A864886F70D0101010500048204AC308204A80201000282010100CEFE8906DA03CC8324F46D15EFC3332A1C385B239675CD0327E84DAFE1D51FF5692475487EA02EB72991A455965A4B9DF156D1996C30B1B3D4F2106B3EE9656E2C808D45DD8262B75C76E87D30B340A55D4081896EA15756E05A9E4B71F9E5CD6BB8C5DA2F6BD5240274777FBB5FD1C65C351DB1260DB9D12EA41F8F59F3EE2D643B6AE37350E5E8B1558FBF655D6309EB809599138D7746B14B8A60A07E5ED67F95A5660C72348F266642B6AE858D22558FB8B8024AE5B2749C0D5E32EBCF0E68422418D3A9214534BD45E526A868A39CC15A1572841A9ECD03D352EABA967EF62317307328138D953A85E11405F60A1CF812A84944D89DE1C34708AD38C1D9020103028201010089FF06049157DDACC34D9E0E9FD7777168259217B9A3DE021A9ADE754138BFF8F0C2F8DAFF15747A1BB66D8E643C32694B8F366648207677E34C0AF229F0EE4973005E2E93AC41CF92F9F05375CCD5C39380565B9F163A39EAE714324BFBEE88F27B2E9174F28E1801A2FA55279536843D78BE76195E7BE0C9C2BFB4E6A29EC7BA816034CED5F9B55BD7A63BA03A231CE22B8110326586BEC6FEFF9E6726240313955BAE60AEB7D63982F8B9939C89F3ADD2820347CFB257E70526EE99A10E17D5B4EF8E05F57178F73CA4350B3A6AB76B397432657E4BABEECDDD002AFAE7CA954A7B8FA8D97425B83F1926950629268FA4F99C4008227CEDFD2890BF4AD5AB0282008100EA8B40FFBE1FFE38CCC3FB4BEDC25C8A543C213CF0040570EF2F66B927654D7868E5458B4DBFF2C007A535925389E2F6F133EA68DA7EEB54CEAB182832E83B96E50FD824F399C3A753F7EFFBCDDD6C4EEBE8E0C82286CAA718540E5BA1C406A0AA9176BC588E2EF93ED22543A068833AA8B880845BCE056A3CEB28EEFB984AC90282008100E1EE19947EEFF11FDACE1B1A0743D1D4440332C3D7F127B7979DA439DE5FDB59795056552DAC2E0DC87C980DFD90DB3DDFA00B4A3C146ED9CB693AD01991FE53C2A2E49ED71F33686DEA5F99C7F35C4190024B01B7BFDE75CE7AF977087E342E6BA1E71C9D53B65BC209BAE3941435159CC81BB98D6A9F783FDC614092B0369102820081009C5CD5FFD4155425DDD7FCDD492C3DB18D7D6B7DF55803A09F74EF261A4388FAF098D907892AA1D55A6E23B6E25BECA4A0CD46F091A9F23889C7657021F027B9EE0A9018A266826F8D4FF552893E48349D45EB301704871A103809926BD8046B1C60F9D2E5B41F50D48C18D7C045ACD1C5D055AD928958F17DF21B49FD1031DB0282008100969EBBB8549FF6153C896766AF828BE2D80221D7E54B6FCFBA691826943FE790FB8AE438C91D74093053100953B5E77E95155CDC280D9F3BDCF0D1E0110BFEE281C1EDBF3A14CCF04946EA66854CE82BB556DCABCFD53EF93451FBA4B05422C99D169A13138D243D2C067C97B80D78B91330127BB39C6A502A92EB8061CACF0B02820080460CD36AC92467D0B5031EE05F8A1D3BE7F1B58DAFAEB932886D3286838F71D81F9431C7A637C4D021EA4447A4279058A7D2441734A44FE4E95E0CA0AD74ECEB72271EAD26921C98E8BCFFE9CDA371E153A08381169DC1898488E61AF4A7252845F03C4AA735766350FBE3D36DAED273B7A922515D724B69B9C06B28EB7FD389
 
Clear data hex: 4A65737569736C65626F737365
clear data ascii:  Jesuislebosse
Encrypted data RSA PKCS1: 8096D0000958AA5F88283BC09AC0574782ADEE311BC4258D6AD5E67736947237B6B1EDEAA78A39DE612D14849E8920A20602F46D044188E8D07FE7236B4770AC01EAF6382B1C3E127AC51D9EF89EF074837FED0DB627974FB45A5B3329AE8B27A466FFC06890F70243509895B060E20659AC76809D18E3E960D47A149844D3EE76B7CDB4105B6E02D00718EB3EC64343658AC74976ED822F52CB0DFC53A0A2F098AF507C23A8FF4E450AF858E2089F3A0CB007C74AF5004B19C8C29AE072C8DF22FDDCC9890808ABF804E1EE06C22B5B0644024B02754974D5717F92B5D8A55B41FD2C62215D0770A040CDEA6D7512D6BB93E75165C6DE3BFC22F69523AB7AEB

I am using the following program:
 *********************************************************
from yubihsm import YubiHsm
from yubihsm.defs import CAPABILITY, ALGORITHM
from yubihsm.objects import AsymmetricKey

import cryptography
from cryptography.hazmat.primitives import hashes, serialization

# Connect to the YubiHSM via the connector using the default password:
hsm = YubiHsm.connect('yhusb://')
session = hsm.create_session_derived(1, 'password')

# Generate a private key on the YubiHSM for creating signatures:
keyvalue = bytes.fromhex("308204C2020100300D06092A864886F70D0101010500048204AC308204A80201000282010100CEFE8906DA03CC8324F46D15EFC3332A1C385B239675CD0327E84DAFE1D51FF5692475487EA02EB72991A455965A4B9DF156D1996C30B1B3D4F2106B3EE9656E2C808D45DD8262B75C76E87D30B340A55D4081896EA15756E05A9E4B71F9E5CD6BB8C5DA2F6BD5240274777FBB5FD1C65C351DB1260DB9D12EA41F8F59F3EE2D643B6AE37350E5E8B1558FBF655D6309EB809599138D7746B14B8A60A07E5ED67F95A5660C72348F266642B6AE858D22558FB8B8024AE5B2749C0D5E32EBCF0E68422418D3A9214534BD45E526A868A39CC15A1572841A9ECD03D352EABA967EF62317307328138D953A85E11405F60A1CF812A84944D89DE1C34708AD38C1D9020103028201010089FF06049157DDACC34D9E0E9FD7777168259217B9A3DE021A9ADE754138BFF8F0C2F8DAFF15747A1BB66D8E643C32694B8F366648207677E34C0AF229F0EE4973005E2E93AC41CF92F9F05375CCD5C39380565B9F163A39EAE714324BFBEE88F27B2E9174F28E1801A2FA55279536843D78BE76195E7BE0C9C2BFB4E6A29EC7BA816034CED5F9B55BD7A63BA03A231CE22B8110326586BEC6FEFF9E6726240313955BAE60AEB7D63982F8B9939C89F3ADD2820347CFB257E70526EE99A10E17D5B4EF8E05F57178F73CA4350B3A6AB76B397432657E4BABEECDDD002AFAE7CA954A7B8FA8D97425B83F1926950629268FA4F99C4008227CEDFD2890BF4AD5AB0282008100EA8B40FFBE1FFE38CCC3FB4BEDC25C8A543C213CF0040570EF2F66B927654D7868E5458B4DBFF2C007A535925389E2F6F133EA68DA7EEB54CEAB182832E83B96E50FD824F399C3A753F7EFFBCDDD6C4EEBE8E0C82286CAA718540E5BA1C406A0AA9176BC588E2EF93ED22543A068833AA8B880845BCE056A3CEB28EEFB984AC90282008100E1EE19947EEFF11FDACE1B1A0743D1D4440332C3D7F127B7979DA439DE5FDB59795056552DAC2E0DC87C980DFD90DB3DDFA00B4A3C146ED9CB693AD01991FE53C2A2E49ED71F33686DEA5F99C7F35C4190024B01B7BFDE75CE7AF977087E342E6BA1E71C9D53B65BC209BAE3941435159CC81BB98D6A9F783FDC614092B0369102820081009C5CD5FFD4155425DDD7FCDD492C3DB18D7D6B7DF55803A09F74EF261A4388FAF098D907892AA1D55A6E23B6E25BECA4A0CD46F091A9F23889C7657021F027B9EE0A9018A266826F8D4FF552893E48349D45EB301704871A103809926BD8046B1C60F9D2E5B41F50D48C18D7C045ACD1C5D055AD928958F17DF21B49FD1031DB0282008100969EBBB8549FF6153C896766AF828BE2D80221D7E54B6FCFBA691826943FE790FB8AE438C91D74093053100953B5E77E95155CDC280D9F3BDCF0D1E0110BFEE281C1EDBF3A14CCF04946EA66854CE82BB556DCABCFD53EF93451FBA4B05422C99D169A13138D243D2C067C97B80D78B91330127BB39C6A502A92EB8061CACF0B02820080460CD36AC92467D0B5031EE05F8A1D3BE7F1B58DAFAEB932886D3286838F71D81F9431C7A637C4D021EA4447A4279058A7D2441734A44FE4E95E0CA0AD74ECEB72271EAD26921C98E8BCFFE9CDA371E153A08381169DC1898488E61AF4A7252845F03C4AA735766350FBE3D36DAED273B7A922515D724B69B9C06B28EB7FD389")
keyvalueSer = serialization.load_der_private_key(keyvalue, password=None, backend=cryptography.hazmat.backends.default_backend())
key = AsymmetricKey.put(session, 0, 'MyDecKey', 1,  CAPABILITY.ALL, keyvalueSer)
print(f"Key loaded: {key}")
bytes.fromhex("272F21C95258F04AF5581894DAECEAD33F13542AE169A7B34CC5F38AD81841B578324D60D172D59380CADB60BCE04D7C6696BDE2AAEFD9ADB2101C76D75F7B7533EFD33ED012EB8601A1BBA9B9D97D8C59C835642CC34D5ABBE22FDA75AF5BCC1A724E2B194CA97CF607C51A4CA03E0062914F75A680097A17E10DE61A6963464E34EB2DEA5BB26B770A40E7897F083E0F1B6E9AF5947D5415BB1A196A43C4F65BD19BD1079A90DDA35F5BA900415AEB8CC9E7E453E2C790878B9A853CBAE3B223595D9227A3B641F972772F2F12577CFC14310A64E9F1CBA3E63E8B067735E4368EF496C76D4B3D5BE38F8EBA0D5BB67BFAEB893D85F4BCDAB99D8ACD3D483A")
dataEnc = bytes.fromhex("8096D0000958AA5F88283BC09AC0574782ADEE311BC4258D6AD5E67736947237B6B1EDEAA78A39DE612D14849E8920A20602F46D044188E8D07FE7236B4770AC01EAF6382B1C3E127AC51D9EF89EF074837FED0DB627974FB45A5B3329AE8B27A466FFC06890F70243509895B060E20659AC76809D18E3E960D47A149844D3EE76B7CDB4105B6E02D00718EB3EC64343658AC74976ED822F52CB0DFC53A0A2F098AF507C23A8FF4E450AF858E2089F3A0CB007C74AF5004B19C8C29AE072C8DF22FDDCC9890808ABF804E1EE06C22B5B0644024B02754974D5717F92B5D8A55B41FD2C62215D0770A040CDEA6D7512D6BB93E75165C6DE3BFC22F69523AB7AEB")
data = key.decrypt_pkcs1v1_5(dataEnc)

print(f"DataDec {data.hex().upper()}")

# Sign some data:
#signature = key.sign_ecdsa(b'Hello world!')  # Create a signature.

# Clean up:
session.close()
hsm.close()
*********************************************************

BR,
Youssiph

**Comment by dainnilsson** [comment] 2022-05-11 09:12
This is a duplicate of https://github.com/Yubico/python-yubihsm/issues/26

**Closed by dainnilsson** 2022-05-11 09:12 UTC
