### ISSUE TITLE
Failed to store symmetric key: Invalid command

### ISSUE THREAD

**Issue by waynethorsted** [Yubico/yubihsm-shell#376] opened 2023-12-08 22:39 UTC
I'm having trouble importing a symmetric key, so I reset the HSM, connected to it, started a session, and cut/paste the command from the document.  
Question: What is wrong with the command, and why can't the reason for the Invalid command be reported instead of the generic error message?

~/HSM$ yubihsm-shell --connector=${YUBIHSM_CONNECTOR}  --authkey=1 --password=password
yubihsm> connect
Session keepalive set up to run every 15 seconds
yubihsm> session open 1
Enter password:
Created session 0
yubihsm> list objects 0
Found 1 object(s)
id: 0x0001, type: authentication-key, algo: aes128-yubico-authentication, sequence: 0, label: DEFAULT AUTHKEY CHANGE THIS ASAP
yubihsm>
yubihsm> put symmetric 0 0 aeskey 1 encrypt-cbc,decrypt-cbc aes128 0a8a7ecc862b3d42b5dc127c111da0f4
Failed to store symmetric key: Invalid command
yubihsm>

**Comment by waynethorsted** [comment] 2023-12-08 23:17
This also fails from cut/paste from document:
yubihsm> generate asymmetric 0 0 aeskey 1 encrypt-ecb,decrypt-ecb aes256
Invalid algorithm 52

I must be doing something basically wrong.

**Comment by aveenismail** [comment] 2023-12-11 08:35
What is the firmware version of your YubiHSM? Support for symmetric keys is available with firmware version 2.3 and later.

See the firmware version by running the command `yubihsm-shell --connector=${YUBIHSM_CONNECTOR} -a get-device-info`. No authentication necessary.

**Comment by waynethorsted** [comment] 2023-12-14 16:34
Thank you for your response.  Yes, that is the issue.  We did not know that symmetric keys were not support when we purchased the HSM's.  Symmetric keys are required for our project.  FIPS certification is not required for our development at this time.  We have opened a ticket at your helpdesk to get the HSM's replaced or updated.   The ticket # is 449175.
Thank you, Wayne

**Comment by aveenismail** [comment] 2023-12-15 07:54
Good to know what the cause of the error was.

I'm closing this issue for now. Please re-open if needed.

**Closed by aveenismail** 2023-12-15 07:54 UTC
