### ISSUE TITLE
YubiHSM 2 not connecting...Need Help

### ISSUE THREAD

**Issue by zhdhasn** [Yubico/yubihsm-shell#261] opened 2022-05-16 06:18 UTC
Ubuntu 20.04.4 LTS (Focal Fossa)

Below listed pkg has been installed manually,

jahid@ubuntu:~/yubihsm2-sdk$ ls
libykhsmauth1_2.3.0-1_amd64.deb     libyubihsm-http1_2.3.0-1_amd64.deb  yubihsm-auth_2.3.0-1_amd64.deb       yubihsm-shell_2.3.0-1_amd64.deb
libykhsmauth-dev_2.3.0-1_amd64.deb  libyubihsm-usb1_2.3.0-1_amd64.deb   yubihsm-connector_3.0.2-1_amd64.deb  yubihsm-wrap_2.3.0-1_amd64.deb
libyubihsm1_2.3.0-1_amd64.deb       README.adoc                         yubihsm-pkcs11_2.3.0-1_amd64.deb
libyubihsm-dev_2.3.0-1_amd64.deb    share                               yubihsm-setup_2.2.0-1_amd64.deb

jahid@ubuntu:~$ yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> debug all
Debug messages enabled
yubihsm> connect
[LIB - INF 06:18:29.298036] yubihsm.c:4162 (yh_init_connector): Loading http backend
[LIB - INF 06:18:29.312767] yubihsm_curl.c:87 (backend_create): backend_create
[LIB - INF 06:18:29.312894] yubihsm_curl.c:92 (backend_connect): backend_connect
[LIB - INF 06:18:29.312916] yubihsm_curl.c:99 (backend_connect): Trying to connect to http://127.0.0.1:12345/connector/status
[LIB - ERR 06:18:29.313671] yubihsm_curl.c:120 (backend_connect): Failure when connecting: 'Failed to connect to 127.0.0.1 port 12345: Connection refused'
[LIB - ERR 06:18:29.313721] yubihsm.c:4199 (yh_connect): Failed when connecting: Unable to find a suitable connector
Failed connecting 'http://127.0.0.1:12345': Unable to find a suitable connector
[LIB - INF 06:18:29.313779] yubihsm_curl.c:152 (backend_disconnect): backend_disconnect
[LIB - INF 06:18:29.313816] yubihsm_curl.c:214 (backend_cleanup): backend_cleanup
yubihsm>

**Comment by zhdhasn** [comment] 2022-05-16 06:22
jahid@ubuntu:~$ curl http://127.0.0.1:12345/connector/status
curl: (7) Failed to connect to 127.0.0.1 port 12345: Connection refused

**Comment by qpernil** [comment] 2022-05-16 12:52
Well that looks like you might not be running the yubihsm-connector, or possibly some local firewall issue making it impossible to reach it. Have you installed yubihsm-connector, and started it ?
To run it without the connector please try with a '-C yhusb://' option added to the command line. With that option the library will use the HSM directly through it's built in usb backend.

**Comment by zhdhasn** [comment] 2022-05-17 03:43
I already install yubihsm-connector_3.0.2-1_amd64.deb.
Not its not connected. Error below,

[LIB - ERR 06:18:29.313671] yubihsm_curl.c:120 (backend_connect): Failure when connecting: 'Failed to connect to 127.0.0.1 port 12345: Connection refused'
[LIB - ERR 06:18:29.313721] yubihsm.c:4199 (yh_connect): Failed when connecting: Unable to find a suitable connector

**Comment by qpernil** [comment] 2022-05-18 12:18
Everything still points to the curl-based http client not being able to connect to the yubihsm-connector at 127.0.0.1 port 12345. Please ensure yubihsm-connector is running on that address and port (the default) and that no local firewall is blocking access to it. The fact that you fail to connect to it with a browser removes the client, ie anything to do with yubihsm-shell and it's libraries from the equation, the issue definitely lies with the connector.

**Comment by zhdhasn** [comment] 2022-05-19 03:58
Okay I am checking. And update you.
Thank you for your assistance.

**Comment by zhdhasn** [comment] 2022-05-25 07:11
system@hsm:~$ yubihsm-connector -d
DEBU[0000] preflight complete                            cert= config= key= pid=2946 seccomp=false serial= syslog=false timeout=0s version=3.0.2
DEBU[0000] takeoff                                       TLS=false listen="localhost:12345" pid=2946

system@hsm:~$ curl http://127.0.0.1:12345/connector/status
curl: (7) Failed to connect to 127.0.0.1 port 12345: Connection refused

system@hsm:~$ yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> debug all
Debug messages enabled
yubihsm> connect
[LIB - INF 07:10:53.701272] yubihsm.c:4162 (yh_init_connector): Loading http backend
[LIB - INF 07:10:53.717913] yubihsm_curl.c:87 (backend_create): backend_create
[LIB - INF 07:10:53.717950] yubihsm_curl.c:92 (backend_connect): backend_connect
[LIB - INF 07:10:53.717961] yubihsm_curl.c:99 (backend_connect): Trying to connect to http://127.0.0.1:12345/connector/status
[LIB - ERR 07:10:53.718167] yubihsm_curl.c:120 (backend_connect): Failure when connecting: 'Failed to connect to 127.0.0.1 port 12345: Connection refused'
[LIB - ERR 07:10:53.718188] yubihsm.c:4199 (yh_connect): Failed when connecting: Unable to find a suitable connector
Failed connecting 'http://127.0.0.1:12345': Unable to find a suitable connector
[LIB - INF 07:10:53.718209] yubihsm_curl.c:152 (backend_disconnect): backend_disconnect
[LIB - INF 07:10:53.718245] yubihsm_curl.c:214 (backend_cleanup): backend_cleanup

Still not solve the issue, Please help me

**Comment by qpernil** [comment] 2022-05-25 08:05
Everything looks good except that you can't connect. That would indicate a local firewall is blocking you.
Since you are on UBuntu this could be used (as an example, you might want to be more specific)
sudo ufw allow 12345
please see here for a tutorial on ufw
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-20-04

**Comment by qpernil** [comment] 2022-05-25 10:55
Have you tried disabling ufw ?

sudo ufw disable

**Comment by qpernil** [comment] 2022-05-25 10:59
And the connector must still be running when you run the yubihsm-shell command, and on the same machine since you are using 127.0.0.1 (localhost)

**Comment by zhdhasn** [comment] 2022-05-26 03:07
I already disable & enable ufw but result remain same.

Connector status:
system@hsm:~$ yubihsm-connector -d
DEBU[0000] preflight complete                            cert= config= key= pid=84410 seccomp=false serial= syslog=false timeout=0s version=3.0.2
DEBU[0000] takeoff                                       TLS=false listen="localhost:12345" pid=84410

**Comment by zhdhasn** [comment] 2022-05-26 03:12
I am checking through SSH to remote server.

system@hsm:~$ yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> connect
Failed connecting 'http://127.0.0.1:12345': Unable to find a suitable connector
yubihsm>

**Comment by zhdhasn** [comment] 2022-05-26 03:33
Current status
Showing Warrning: WARN[0033] status failed to open usb device
system@hsm:~$ yubihsm-connector -d
DEBU[0000] preflight complete                            cert= config= key= pid=89735 seccomp=false serial= syslog=false timeout=0s version=3.0.2
DEBU[0000] takeoff                                       TLS=false listen="localhost:12345" pid=89735
DEBU[0033] usb context not yet open                      Correlation-ID=5f2097f6-f770-444c-bcf3-8b37f3bcd328
WARN[0033] status failed to open usb device              X-Request-ID=5f2097f6-f770-444c-bcf3-8b37f3bcd328 error="libusb: bad access [code -3]"
INFO[0033] handled request                               Content-Length=0 Content-Type= Method=GET RemoteAddr="127.0.0.1:52050" StatusCode=200 URI=/connector/status User-Agent="YubiHSM curl/2.3.0" X-Real-IP=127.0.0.1 X-Request-ID=5f2097f6-f770-444c-bcf3-8b37f3bcd328 latency=6.872022ms
WARN[0046] status failed to open usb device              X-Request-ID=6c197081-382a-4945-a223-0931c03055da error="libusb: bad access [code -3]"
INFO[0046] handled request                               Content-Length=0 Content-Type= Method=GET RemoteAddr="127.0.0.1:52052" StatusCode=200 URI=/connector/status User-Agent="YubiHSM curl/2.3.0" X-Real-IP=127.0.0.1 X-Request-ID=6c197081-382a-4945-a223-0931c03055da latency="309.489µs"

And the Shell status:

Showing : [LIB - INF 03:22:01.857258] lib_util.c:140 (parse_status_data): has device: no

yubihsm> connect
[LIB - INF 03:22:01.846909] yubihsm.c:4162 (yh_init_connector): Loading http backend
[LIB - INF 03:22:01.856143] yubihsm_curl.c:87 (backend_create): backend_create
[LIB - INF 03:22:01.856194] yubihsm_curl.c:92 (backend_connect): backend_connect
[LIB - INF 03:22:01.856205] yubihsm_curl.c:99 (backend_connect): Trying to connect to http://127.0.0.1:12345/connector/status
[LIB - INF 03:22:01.857230] lib_util.c:139 (parse_status_data): response from connector
[LIB - INF 03:22:01.857258] lib_util.c:140 (parse_status_data): has device: no
[LIB - INF 03:22:01.857271] lib_util.c:141 (parse_status_data): version: 3.0.2
[LIB - INF 03:22:01.857283] lib_util.c:143 (parse_status_data): pid: 89735
[LIB - INF 03:22:01.857295] lib_util.c:144 (parse_status_data): address: localhost
[LIB - INF 03:22:01.857307] lib_util.c:145 (parse_status_data): port: 12345
[LIB - ERR 03:22:01.857317] yubihsm_curl.c:140 (backend_connect): Failure when connecting: Connector has no device
[LIB - ERR 03:22:01.857339] yubihsm.c:4199 (yh_connect): Failed when connecting: Unable to find a suitable connector
Failed connecting 'http://127.0.0.1:12345': Unable to find a suitable connector
[LIB - INF 03:22:01.857364] yubihsm_curl.c:152 (backend_disconnect): backend_disconnect
[LIB - INF 03:22:01.857436] yubihsm_curl.c:214 (backend_cleanup): backend_cleanup

**Comment by zhdhasn** [comment] 2022-05-26 03:59
system@hsm:~$ curl http://127.0.0.1:12345/connector/status
status=NO_DEVICE
serial=*
version=3.0.2
pid=89735
address=localhost
port=12345

**Comment by qpernil** [comment] 2022-05-27 08:11
OK, so now we have a different situation, now the problem is that the connector doesn't have access to the usb device.
Please see the end of this page for some udev rules to enable non-root access to the hsm: https://developers.yubico.com/YubiHSM2/Component_Reference/yubihsm-connector/
You could also, for testing purposes, run the connector as root.

**Comment by zhdhasn** [comment] 2022-05-28 05:31
Thank You,
Now Problem has been solve.
one query, Is yubihsm-connector -d terminal is always open ?

**Comment by aveenismail** [comment] 2022-06-01 13:17
Since you're using a Debian based system, you can set the `yubihsm-connector` to run as a service. To do so, create a service file, tex `yubihsm-connector.service` in `/etc/systemd/system` with the following content

```
[Unit]
Description=YubiHSM Connector
After=network.target

[Service]
Type=simple
Restart=always
ExecStart=<PATH TO yubihsm-connector binary>

[Install]
WantedBy=multi-user.target
```

Run the following commands to reload and enable the service
```
$ systemctl daemon-reload
$ systemctl enable yubihsm-connector.service
```

To start the service, run

`$ systemctl start yubihsm-connector.service`

To stop the service, run

`$ systemctl stop yubihsm-connector.service`

See https://wiki.debian.org/systemd/Services for reference.

**Comment by qpernil** [comment] 2022-06-01 14:39
And to answer your question - starting yubihsm-connector like that will not detach it, with or without the -d flag. So Yes.

**Comment by qpernil** [comment] 2022-06-03 15:07
Closing this ossue now as it seems to be solved. Please open a new issue if needed.

**Closed by qpernil** 2022-06-03 15:07 UTC

**Comment by zhdhasn** [comment] 2022-06-05 06:18
Thank you very much Per Nilsson and Aveen Ismail
